// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace HomeRun.RatingService.Migrations
{
    [DbContext(typeof(RatingDbContext))]
    partial class RatingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeRun.NotificationService.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceProviderXId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderXId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("HomeRun.RatingService.Models.ServiceProviderX", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviderX");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 1, 15, 41, 57, 421, DateTimeKind.Utc).AddTicks(5397),
                            Name = "ProviderA"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 1, 15, 41, 57, 421, DateTimeKind.Utc).AddTicks(5459),
                            Name = "ProviderB"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 8, 1, 15, 41, 57, 421, DateTimeKind.Utc).AddTicks(5470),
                            Name = "ProviderC"
                        });
                });

            modelBuilder.Entity("HomeRun.NotificationService.Entities.Rating", b =>
                {
                    b.HasOne("HomeRun.RatingService.Models.ServiceProviderX", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ServiceProviderXId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeRun.RatingService.Models.ServiceProviderX", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
